# Generated by Django 5.0.1 on 2024-01-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_university_user_bio_user_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='alpha_two_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='state_province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
