# Generated by Django 5.0.1 on 2024-02-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_email_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
