# Generated by Django 5.0.1 on 2024-02-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_email_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_subjects',
            field=models.TextField(null=True),
        ),
    ]
