# Generated by Django 5.0.1 on 2024-02-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutoring_pay',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
