# Generated by Django 5.0.1 on 2024-02-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.university'),
        ),
    ]
