# Generated by Django 5.0.1 on 2024-02-08 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studygroup_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.university'),
        ),
    ]
