# Generated by Django 5.0.1 on 2024-02-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
