# Generated by Django 5.0.1 on 2024-02-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user_zip_code_delete_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutoring_enabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
