# Generated by Django 5.0.1 on 2024-02-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_tutoring_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tutoring_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
