# Generated by Django 5.0.1 on 2024-02-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_studygroup_university'),
        ('main', '0014_alter_user_tutoring_enabled'),
    ]

    operations = [
    ]
