# Generated by Django 5.0.1 on 2024-02-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_notification'),
        ('main', '0015_merge_20240217_1537'),
    ]

    operations = [
    ]
