# Generated by Django 5.0.1 on 2024-03-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='regarding_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regp_set', to='main.grouppost'),
        ),
    ]
