# Generated by Django 5.0.1 on 2024-02-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_user_tutoring_pay_alter_user_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
