# Generated by Django 5.0.1 on 2024-03-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_notification_regarding_post'),
        ('main', '0021_remove_message_seen_recipient_group_name'),
    ]

    operations = [
    ]
