# Generated by Django 5.0.1 on 2024-03-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_groupchat_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meet_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(default='location', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(default='desc', max_length=500),
            preserve_default=False,
        ),
    ]
