# Generated by Django 5.0.1 on 2024-03-26 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_groupchat_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipents',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
