# Generated by Django 5.0.1 on 2024-03-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_meet_time_meeting_time_meeting_duration_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
