# Generated by Django 5.0.1 on 2024-03-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='overall',
            field=models.IntegerField(default=5),
        ),
    ]
