# Generated by Django 5.0.1 on 2024-03-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_review_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
