# Generated by Django 5.0.1 on 2024-04-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_meeting_description'),
        ('main', '0030_user_average_rating'),
    ]

    operations = [
    ]
