# Generated by Django 5.0.1 on 2024-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_message_recipents_rename_text_message_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmid', models.CharField(max_length=100, unique=True)),
                ('student', models.CharField(default='', max_length=100)),
                ('tutor', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
