# Generated by Django 5.0.1 on 2024-04-16 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_message_dmid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentDMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipient_group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
