# Generated by Django 5.0.1 on 2024-04-23 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_currentdmuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='regarding_dm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regdm_set', to='main.recipient_group'),
        ),
    ]
